# Generated by Django 4.2 on 2023-05-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
