# Generated by Django 3.1.8 on 2023-05-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
